### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by DarrachBarneveld** [ai-avenger-teams/rebuild-ireland-backend#2]
Design wireframes for the application, covering key screens.

Sample pages: 

- Home, 
- Login/Sign-Up, 
- Dashboard 
- Prompting
- Settings
- Information

Focus on layout, user flow, and primary UI elements.

Include navigation elements and key functionalities.

**Comment by stephendawsondev** [comment]
Love the look of these wireframes!
